### PR TITLE
Type alias for expected return codes

### PR DESCRIPTION
**Pull request by eugeneoden**
Simple change to alias c_int as ssh_return_code.

I'm working on a safe wrapper for this crate and adding a type alias here will help.

### CODE REVIEW

**Comment by cuviper** [comment]
Hi, thanks for your interest!

Generally for FFI declarations, I try to keep the raw API looking similar to the foreign source. So the original source declares functions like:

```c
LIBSSH_API int ssh_connect(ssh_session session);
```

and in this crate we have:

```rust
pub fn ssh_connect(session: ssh_session) -> c_int;
```

So the `int`/`c_int` do match, and I'm hesitant to obscure this with a new type alias. There's nothing called `ssh_return_code` in the libssh headers.

Can you explain why it would help you? Is that just for documentation purposes, for the _expected_ `int` values it may return?

**Comment by eugeneoden** [comment]
Fair enough.

I'm fairly new to Rust but I was looking at using this 'ssh_return_code' type alias in an 'impl From' to transform c_int return codes into Rust enums.  I'll look into alternatives.

**Comment by cuviper** [comment]
Note that Rust type aliases are completely identical to the compiler, so `From<ssh_return_code>`, `From<c_int>`, and `From<i32>` all mean exactly the same thing. If you actually want a distinct type, you would need the newtype pattern of a struct wrapping the original type, often a tuple struct like `struct MyType(c_int)`.

**Comment by eugeneoden** [comment]
Ah, makes sense.  Thanks.

**Pull request closed without merging**
